### PR TITLE
add ability to filter xworkspace names with regex

### PR DESCRIPTION
**Pull request by maxaudron**
new property filter: takes regex expression and
 matches them against the workspace names filtering
 out all that don't match

### CODE REVIEW

**Comment by patrick96** [comment]
Is this ready to be reviewed or is there still something that you need to change?

I think this approach breaks the `%index%` token and the click functionality (which relies on the workspace index) since the index is calculated based on the size of the `m_desktop_names` list which is changed here.

**Comment by maxaudron** [comment]
Yep i noticed that shortly after opening the pull request. I'll rework it hopefully by the weekend

**Comment by maxaudron** [comment]
@patrick96 should be good to go now

**Comment by maxaudron** [comment]
im closing this as i am no longer in need for it and never got it to fully work in the first place.

**Pull request closed without merging**
