### PR TITLE
Release 3.5.0

### PR DESCRIPTION
**Pull request by patrick96**
## What type of PR is this? (check all applicable)

* [ ] Refactor
* [ ] Feature
* [ ] Bug Fix
* [ ] Optimization
* [ ] Documentation Update
* [x] Other: Release PR

## Description

After almost 1.5 years, the next minor polybar release :fireworks:

I will write up a release blog post in the next few days and then we can merge this.

The drafted GitHub release can be found [here](https://github.com/polybar/polybar/releases/tag/untagged-2c9ce51665cc0c122bde) (visible to polybar team only).

Post release-checklist:

* [ ] Remove "Click Commands are not Executed" from known issues.
* [ ] Use `notice` log level in font debugging wiki page
* [ ] Add config syntax link to "Configuration" page
* [ ] Remove ["With multiple modules of the same type, actions on those modules control the leftmost module"](https://github.com/polybar/polybar/wiki/Known-Issues#with-multiple-modules-of-the-same-type-actions-on-those-modules-control-the-leftmost-module) from the known issues
* [ ] Remove the note on the menu module page that only a single menu module can exist.
* [ ] Add a note about migration to all the wiki pages that use the legacy action names:
  * [ ] i3 module
  * [ ] bspwm module
  * [ ] menu module
  * [ ] ipc (not the module)
  * [ ] (maybe others)
* [ ] Mark all deprecations in the wiki
* [ ] Remove all unreleased notes from the wiki
* [ ] Add release information to #1971
* [ ] Upload release archive
* [ ] Update PKGBUILDs
* [ ] Publish Blog Post (https://github.com/polybar/polybar.github.io/pull/17)
* [ ] Post blog post to reddit, gitter, IRC.

Breaking Changes:

* The new config parser imposes some restrictions on which characters can be
  used in section and key names. Users shouldn't be affected by this unless they
  use one of the following characters in any section or key name: `"'=;#[](){}:.$\%`
  Please consult [`man 5 polybar`](https://polybar.readthedocs.io/en/latest/man/polybar.5.html) for a full reference of the new config rules.
* `internal/temperature`: The first and last ramp element are now only used for
  `base-temperature` and below and `warn-temperature` and above respectively.
  This only slightly changes the ranges for which the different ramp levels are
  responsible for.
  (#2197)

Changelog

**Deprecations**

* `[settings]`: `throttle-input-for` has been removed. It wasn't a useful option
  and could cause certain actions (e.g. click commands) to be ignored. (#2117)

* All action names used by modules to handle click and scroll events are
  depercated (#1907).  This change mainly affects users of the menu module.
  Please read the [documentation](https://polybar.readthedocs.io/en/latest/user/actions.html) for instructions on how to migrate.

**New Config Options**

The `include-directory` key can be used the same as `include-file` and includes
all regular files in the given directory.

In labels:

* `label-NAME-minlen`, `label-NAME-alignment` can be used to pad labels with
  spaces to the right (alignment set to `left`), left (alignment set to
  `right`), and both sides (alignment set to `center`).

In `internal/backlight`:

* `enable-scroll` enables changing the brightness through scrolling.

In `internal/github`:

* `format-offline` is used when the module cannot connect to the server.
* `label-offline` can be used in `format-offline`.
* `api-url` can be used to connect to a custom github enterprise instance

In `internal/pulseaudio`:

* `click-right` and `click-middle` can be used to execute commands when
  right/middle clicking.
* `%decibels%` token can be used in `label-volume` and `label-muted` to show the
  volume in decibels.

**Changes To The Build System**

* Allow users to specify python executable when building. (polybar/xpp#27,
  #2125)
* The i3ipcpp submodule no longer rebuilds jsoncpp and just uses whatever
  version is available. (#2015, polybar/i3ipcpp#9)

**Features**

* New commandline argument: `-M` / `--list-all-monitors`.
    Will display all available monitors (even cloned ones).
* New log level: `notice`.
    Used as the default and is used for non-warning messages the user should
    nevertheless be aware of. (#2027)
* config:
    * New config parser (#1377)
    * `include-directory` key (#2196), see #1946
    * Add error message when an entire section is missing. (#2195)
    * `-minlen` and `-alignment` properties for labels. (#1546)
    * Make the `seperator` key in the bar section a label. (#1918)
    * Better color validation. (#1290)
* timer modules: Schedule module updates to be aligned with the update interval.
  For example, the date module now updates on the minute instead of in the
  middle of a minute if the interval is set to 60 seconds. (#2123), see #2064
* `custom/menu`: Multiple menu modules per bar (#1907)
* `internal/backlight`: Support for changing the brightness through scrolling.
  This may require additional changes to the system running polybar. (#1957)
* `internal/github`:
    * `format-offline` for when the module cannot connect to the server (#1825),
    see #1815
    * Support for github enterprise instances. (#1841), see #1812
* `internal/network`: Support `Gbit/s` for `%linkspeed%` token. (#2055)
* `internal/pulseaudio`:
    * `click-right` and `click-middle` keys (#1941)
    * `%decibels%` token (#1894), see #1886
* `internal/xworkspaces`: Proper implementation for `label-occupied`. (#822),
  see #874, #1444, #1033

**Fixes**

* Polybar not executing commands that produce output. (#1680), see #916
* Polybar froze until click commands finished executing (#2248)
* Polybar not properly working with mirrored monitors. (#1823), see #1192 and
  #1794
* Unstable animation framerate (#1683), see #568
* Multiple modules of the same type caused click events not to be delivered to
  the rigth one (#1907), see #1172
* config:
    * Seemingly unrelated error messages when BOM character appears in config.
    (#2166), see #2075
    * Fall back to next possible config location if config file doesn't exist
      (except if `--config` was used). (#2026), see #2016
* iconset: `fuzzy-match` chose first match, even if exact match was available.
  (#2042), see #2041
* `custom/menu`: Spacing issue (#1656)
* `internal/alsa`: Volume didn't go over 100% (#2184), see #2173
* `internal/backlight`: Use amdgpu workaround for all devices starting with
  `amdgpu_bl`. (#2122)
* `internal/battery`: Battery not marked as full if over `full-at` percent.
  (#2019), see #1622
* `internal/cpu`: More accurate cpu load calculation. (#1955)
* `internal/github`: Outdated GitHub API authentication. (#2029), see #2002
* `internal/memory`: Use the correct size prefixes (#2211), see #2023
* `internal/network`:
    * Wrong up- and downspeed values for non-integer intervals. (#2219)
    * tun/tap interfaces didn't query their IP addresses. (#1990), see #1986
    * Don't crash module if linkspeed cannot be queried. (#1772), see #1211
* `internal/temperature`:
    * `format-warn` was not used if the temperature was *exactly*
      `warn-temperature`. (#1897)
* `internal/xworkspaces`:
    * Multi-monitor issue (#1929), see #1764, #1849
    * Module sometimes showed too many workspaces (#1984), see #1983
* build:
    * xpp submodule doesn't work with python 3.9 (polybar/xpp#26)
    * CMake 3.17+ developer warnings (#2089, polybar/xpp#24, polybar/xpp#25)
    * gtest compilation failure (#1993), see google/googletest#2678
    * Compilation issue in GCC 6. (#1953)

## Related Issues & Documents

This is the first release that follows the release guidelines layed out int #2185 and #1780

## Documentation (check all applicable)

* [ ] This PR requires changes to the Wiki documentation (describe the changes)
* [ ] This PR requires changes to the documentation inside the git repo (please add them to the PR).
* [x] Does not require documentation changes

### CODE REVIEW

**Comment by patrick96** [comment]
I added the fix for #2255 to this PR, just before the release commit. We can't really publish 3.5.0 without this fix.

**Comment by patrick96** [comment]
@markring40-git I don't appreciate your tone. If you can't be civil, then we have nothing to talk about. If you can, I am more than happy to have a discussion about this.

Which of the now forbidden characters do you use in your key or header names?

We basically forbid any character that has a special meaning in polybar. This ensures that none of our parsers have to parse a string that has multiple different interpretations. Before this update it was completely possible for one of our parsers to encounter a string with multiple different ways to parse, in that case, the parser would just do something, but probably not the thing you would have expected.

**Comment by markring40-git** [comment]
I’m interested in hearing about the changes made; your opinion of my tone not withstanding.

Also, I’m interested in why there was an apparent lack of interest in what the community in general might want?

Or why not forewarn users that substantial impacts may result from  an upcoming release?

Mark Ring

**Comment by patrick96** [comment]
We did not expect this to have an impact at all and definitely not a big one. Reason being that none of the config keys natively used by polybar use any forbidden characters (obviously) and our documentation never did either.
I have also never seen any config that used anything other than alphanumeric characters, dashes, underlines and slashes for its keys and section names, in fact, most people only use custom keys to define colors.

In the 16 months that this change has been on `master`, we did not receive any reports that this broke someone's config and normally bigger issues with changes on `master` are reported within weeks.

If we got the sense that this would substantially impact people, we would have communicated this more publicly beforehand, or not even released the changes until version 4.0, but we never got any indication that it would.

**Comment by markring40-git** [comment]
If you don’t mind. I’ll send you a copy of my config. It’s a combination of other configurations, my own additions and cutting and pasting from your site a GitHub.  It worked fantastically until the most recent update.  So I’m a little confused by your response.

Mark Ring
markring40@gmail.com
715-563-5573

**Comment by patrick96** [comment]
I would certainly be interested to see what kind of usecases these now forbidden characters had in people's config.

**Pull request merged**
