### PR TITLE
Use an option to customize how space is inserted in the bars

### PR DESCRIPTION
**Pull request by DRKblade**
# The problem
Polybar currently use the space character as the unit of margin/padding. But the size of space characters is dependent of the font used in `font-0` option, which means an update of all the space sizes is needed after changing the font.

## Some unsatisfying solution
* A solution is to use a font for margin/padding space and another font for normal text, but the text font have to be set for every module used as there is no global font setting yet.
* Another solution is the `separator` option, but it only affect the margin between modules and not the padding.

# My solution
I decide to create `space-unit` as an option as it allows for a more consistent character to be used as the unit of space (such as the em/en space). Also with this option, the user can scale all the margin/padding in the bar by changing this option.

### CODE REVIEW

**Comment by patrick96** [comment]
I don't see how the space unit solves your original problem. The regular space, em space, and en space all dependent on the font and/or font size, so if you change your font(size), you will still change all your space sizes.

**Comment by DRKblade** [comment]
In the case even the em space and en space aren't consistent. The user can still change the space size by changing the number of space characters in `space-unit` instead of having to change all the margin and padding fields every time they change the font.

But with `space-unit`, you can use the em space, a character that doesn't appear in normal texts, as the unit, then use an icon font that provides em space but not normal text characters as `font-0` and finally the font for normal text as `font-1`. That way, the font and font size of normal texts can be changed without changing the spacing.

**Comment by patrick96** [comment]
I see your point.

Has the size of the spacing been a problem for you when you change your text font? I would have thought that having the space size tied to your text font would be a good thing because it was designed to look natural with the rest of the text.

There was already some work done to allow users to specify padding and margin as other things than just spaces (pixels and points). I think that would address your problem as well: #1671

**Comment by DRKblade** [comment]
I do encounter problems with spacing when changing fonts, as shown [here](https://imgur.com/a/c2rlhZc).
But using other units of space would be the better solution to my own, so I'm looking forward to that feature. In the meantime though, I will keep using this as a temporary solution.

**Comment by patrick96** [comment]
Closing in favor of #1671

**Pull request closed without merging**
