### PR TITLE
travis: create an irc one-liner

### PR DESCRIPTION
**Pull request by x70b1**
Combine the information into one line.

### CODE REVIEW

**Comment by Lomadriel** [comment]
So if I'm not wrong.
`" %{repository_slug}(%{branch})#%{build_number} | \"%{commit_subject}\" by %{author} | Commit #%{commit} %{result}"`
would result in something like this:
`polybar/polybar(develop)#1000 | "travis: create an irc one-liner" by x70b1 | Commit #sha success`

Wouldn't it be better to use `%{repository_name}` rather than `%{repository_slug}` since in theory, the organization name is always the same?

Otherwise I'm not using the IRC so much (for now), so I'll let the review to @patrick96 but it seems good to me.

**Comment by x70b1** [comment]
The problem is that even forked projects will start posting in the IRC channel if they activate travis.

The argument for the slug is that it is the only way to quickly recognize that it is the repository from the organization.

**Comment by Lomadriel** [comment]
Indeed, we should use `%{repository_slug}` in this case. Is there a way to block this?
I don't think we really want forked projects to push notification on our IRC channel if they activate travis.

**Comment by x70b1** [comment]
At the moment there is no simple solution. But it's not a big problem either, because forked projects very rarely enable Travis.

**Comment by x70b1** [comment]
I tested that already here: https://github.com/polybar/polybar-scripts/commit/313ff76cb66a8600ca6f6f1a8d39cec4f7324a87. 

It didn't work in this first attempt. Patrick had no success too at this. If its gonna be a problem, we could try it again. We decided its ok for the moment.

**Comment by Lomadriel** [comment]
> It didn't work in this first attempt. Patrick had no success too at this. If its gonna be a problem, we could try it again. We decided its ok for the moment.

I agree with you, I don't think this will cause problems for now.

**Comment by x70b1** [comment]
:rocket:

**Pull request merged**
