### PR TITLE
updated ramp.cpp

### PR DESCRIPTION
**Pull request by akshitbansal2005**
## What type of PR is this? (check all applicable)

* [ ] Refactor
* [ ] Feature
* [ ] Bug Fix
* [ ] Optimization
* [ ] Documentation Update
* [ ] Other: *Replace this with a description of the type of this PR*

## Documentation (check all applicable)

* [ ] This PR requires changes to the Wiki documentation (describe the changes)
* [ ] This PR requires changes to the documentation inside the git repo (please add them to the PR).
* [ ] Does not require documentation changes

### CODE REVIEW

**Comment by patrick96** [comment]
Hacktoberfest spam, just like the other four PRs: #3174, #3175, #3176, #3177

The commit messages very much look like they were generated by chatgpt or similar (at least I'm getting very similar output when uploading those files to chatgpt).
The code is most likely generated the same way, it's nowhere close to actually compiling

Do better

**Comment by akshitbansal2005** [comment]
Hey can you please remove me as a spam I got disqualified from
hacktoberfest and I haven't done anything please it would be very grateful
if you could remove me as a spam.

**Comment by akshitbansal2005** [comment]
Hey can you please remove me as a spam I got disqualified from
hacktoberfest and I haven't done anything please it would be very grateful
if you could remove me as a spam because it takes alot of hardwork and
dedication in debugging of code and analysis of the code

**Comment by akshitbansal2005** [comment]
please if possible do something its a request to you i had done alot of hardwork and it was my first time in hacktoberfest

**Comment by patrick96** [comment]
The PRs are marked as spam because you are spamming. Just in this repo, you opened 5 low-quality pull requests within 17 minutes. They either don't have any description at all, or it was AI generated.
The code is also most likely AI generated and doesn't even compile, so you didn't even try to test it.

You've also done the same thing in tons of other repositories:

2024-10-19-201642_758x646_scrot

This kind of thing takes away resources from maintainers, goes against the hacktoberfest values, and is just generally annoying

**Comment by akshitbansal2005** [comment]
You can't do anything?

**Pull request closed without merging**
