### PR TITLE
build: Update xpp module

### PR DESCRIPTION
**Pull request by patrick96**
Fixes developer warnings in cmake 3.17+

Ref: polybar/xpp#24

### CODE REVIEW

**Comment by Lomadriel** [comment]
Hum it doesn't seem to compile on travis

**Comment by patrick96** [comment]
That's weird. This is actually the invocation of `find_package_handle_standard_args` where I barely changed anything and according to the cmake docs my change shouldn't have changed any functionality.

I will try to debug this in a VM with an older cmake version.

**Comment by patrick96** [comment]
:man_facepalming: Older cmake version interpret the `NAME_MISMATCHED` flag as a variable it needs to check instead of as a flag.

I guess we're not getting around using `FPHSA_NAME_MISMATCHED`. I will quickly push that change to xpp and then update this PR

**Comment by patrick96** [comment]
> I hope it works for all versions x)

It should the function signature I used exists since cmake 3.0

**Pull request merged**
