### PR TITLE
internal/backlight - add use-actual-brightness option

### LINKED ISSUE #2367: backlight module is "delayed"
## Checklist

* [x] I have read the appropriate section in the [contributing
  guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
* [x] I believe this issue is a problem with polybar itself and not a misconfiguration on my part.
* [x] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that
  may have already reported this problem.
* [x] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.

## Describe the bug

With the backlight module, the brightness bar is "delayed". I.e. when I first change it, the bar doesn't change, and when I change it again, the bar changes to what it was before the current change.
**Expected behavior:**

Backlight label/bar should change when brightness is changed

**Actual behavior:**

Delayed behaviour explained before

**Was it working before?**
* Did you also experience this bug in an earlier version of polybar (yes/no/don't know)? no
* If no, what was the last version where this worked correctly? None, I just installed it

## To Reproduce

```dosini
[module/backlight-acpi]
inherit = module/xbacklight
type = internal/backlight
card = amdgpu_bl0

label = %percentage%% brightness
interval = 5
```

Change your brightness with something like this in your i3 config:
```
bindsym XF86MonBrightnessUp exec --no-startup-id brightnessctl s +5%
bindsym XF86MonBrightnessDown exec --no-startup-id brightnessctl s 5%-
```

Must have `brightnessctl` installed. You can also just `brightnessctl s +5%` or `brightnessctl s 5%-`.

## Polybar Log

```
notice: Parsing config file: /home/swirl/.config/polybar/config
error: Disabling module "bspwm" (reason: Could not find socket: /tmp/bspwm_0_0-socket)
error: module/mpd: Connection refused
notice: pulseaudio: using default sink alsa_output.pci-0000_03_00.6.analog-stereo
error: module/mpd: Connection refused
notice: Loaded font "fixed:pixelsize=10" (name=Nimbus Sans, offset=1, file=/usr/share/fonts/gsfonts/NimbusSans-Regular.otf)
notice: Loaded font "unifont:fontformat=truetype:size=8:antialias=false" (name=Droid Sans, offset=0, file=/usr/share/fonts/droid/DroidSans.ttf)
notice: Loaded font "siji:pixelsize=10" (name=Nimbus Sans, offset=1, file=/usr/share/fonts/gsfonts/NimbusSans-Regular.otf)
warn: Systray selection already managed (window=0x1200009)
```

## Environment:
* WM: i3-gaps
* Distro: Artix Linux
* Output of `polybar -vvv`:

```
polybar 3.5.4

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags: -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wall -Wextra -Wpedantic -O3 -DNDEBUG
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
```

### PR DESCRIPTION
**Pull request by binex-dsk**
## What type of PR is this? (check all applicable)

* [ ] Refactor
* [ ] Feature
* [x] Bug Fix
* [ ] Optimization
* [ ] Documentation Update
* [ ] Other: *Replace this with a description of the type of this PR*

## Description

Adds a `use-actual-brightness` option to `internal/backlight`, which specifies whether to use the `actual_brightness` file in `/sys/class/backlight/%card%/` or the `brightness` file. Defaults to true **unless** the card is an amdgpu card.

## Related Issues & Documents

Fixes/closes #2367

## Documentation (check all applicable)

* [x] This PR requires changes to the Wiki documentation (describe the changes)
* [ ] This PR requires changes to the documentation inside the git repo (please add them to the PR).
* [ ] Does not require documentation changes

https://github.com/polybar/polybar/wiki/Module:-backlight - needs the `use-actual-brightness` option documented.

### CODE REVIEW

**Review by patrick96 — CHANGES_REQUESTED** [review]
Looks good. Please also mention the name of the option and the name of the module in the changelog message. After that I'll merge this.

**Comment by binex-dsk** [comment]
@patrick96 done

**Review by patrick96 — APPROVED** [review]

**Comment by patrick96** [comment]
Thanks :+1:

**Comment by binex-dsk** [comment]
ok this randomly popped back into my brain again so i updated the wiki now

**Comment by patrick96** [comment]
Cool 😃

**Pull request merged**
