### PR TITLE
readme: Remove GetDeb mention

### PR DESCRIPTION
**Pull request by patrick96**
GetDeb.net has been offline for a month and isn't looking like coming
back up. Now there isn't even a DNS record anymore.

### CODE REVIEW

**Comment by kronn** [comment]
I support this step. There is no use in mentioning this. Even before, it was outdated. Are there any alternatives for deb-packages on the horizon?

**Comment by patrick96** [comment]
In #1054 there was someone trying to package for the debian official repo but I haven't heard anything back yet. Packaging precompiled binaries is an issue anyway right now because if polybar is compiled with let's say i3 support you need to have i3 installed to even run that polybar executable (see #1406).

Until this is resolved it will be quite difficult for someone to actually properly package polybar in any official repository. Had someone on IRC the last few days that ran into the same roadblocks.

**Comment by kronn** [comment]
@patrick96 Ah, thanks for clarifying. I was hoping it was "just" a matter of setting up a build-pipeline or even a PPA that could be filled by `$CI_SAAS`.

**Comment by patrick96** [comment]
I don't know how feasible it would be to set that up but if it's possible we would certainly be open to that once we finished the plugin architecture.

**Pull request merged**
