### PR TITLE
build: Update i3ipcpp submodule

### PR DESCRIPTION
**Pull request by patrick96**
With this we no longer distribute the jsoncpp 1.7.7 source with polybar.
It is possible that polybar will no longer build on older systems that
have an ancient version of jsoncpp (>= 5 years).

Ref: polybar/i3ipcpp#9

### CODE REVIEW

**Comment by Lomadriel** [comment]
Shouldn't we update the dependencies ?

**Comment by patrick96** [comment]
Which dependencies?

**Comment by samueloph** [comment]
Just giving a suggestion, if you're aware of a minimum version required for the lib that polybar needs to work, you can declare that in the README, so packagers will be aware of that.

But I don't think you're gonna have problems with any distro, the ones which are old enough for this be an issue are not packaging the latest releases, and if they are, they can also package the newer lib.

**Comment by patrick96** [comment]
The problem is, we're not really aware of a minimum version :man_facepalming: 

The i3ipcpp project did compile version 1.7.7 if a more recent version couldn't be found, but in your package, you just decrease that to 1.7.4, so versions lower than 1.7.7 seem to work, we just don't know how far down.

**Comment by samueloph** [comment]
@patrick96 that's ok, it's very common to not be aware of required version of dependencies, and in this case you can just ignore it until some issue arrives. But I'm pretty sure that no issue will show up, as we know that an "old enough" version is supported.

**Comment by Lomadriel** [comment]
> Which dependencies?

My bad, "jsoncpp" was already in the dependency list :man_facepalming:

**Pull request merged**
