### PR TITLE
Improves date module (label for alternative and timezone support)

### LINKED ISSUE #596: Select time zone for date module
It'd be extremely handy to be able to select which time zone a date module displays. Even just "utc = true" would be useful.

### LINKED ISSUE #1293: [module/date] Zone and UTC feature support request
Hello,

That's why I request to:

- Each user may want to see their own time zone. (Like I would like to see the time of Turkey and my brother may want to see Germany time.)
- We don't have to change the `zoneinfo` information from `/usr/share/` specially
- What time zone do we want to see ? LocalTime, UTC, Network Synched, etc...
- TimeZone offset support? UTC+1, UTC+2 like that.

Edit: Oh I forgot that trick, each user can have their own time zone. :)

Currently only localtime support is available with the [date] architecture. When we do `timedatectl`, there are few outputs:

```
Local time: Wed 2018-06-20 14:02:29 +03
Universal time: Wed 2018-06-20 11:02:29 UTC
RTC time: Wed 2018-06-20 14:02:29
Time zone: Europe/Istanbul (+03, +0300)
System clock synchronized: no
```

But Polybar uses localtime everytime as long as I do not sync with localtime to network time using timezones from mentioned here https://wiki.archlinux.org/index.php/Time#Time_zone

I don't think that's a rational solution for Polybar. The time module should be further improved. The module I designed in my mind is:

```
[module/date]
type = internal/date

; New date features
timezone = Europe/Istanbul ; from /usr/share/zoneinfo
timezoneoffset = +3, +2, 0, bla bla...
datetype = UTC, RTC, Local, Universal etc...
autosync = true ; Possibility of system time not synced


; Seconds to sleep between updates
interval = 1.0

; See "http://en.cppreference.com/w/cpp/io/manip/put_time" for details on how to format the date string
; NOTE: if you want to use syntax tags here you need to use %%{...}
date = %Y-%m-%d%

; Optional time format
time = %H:%M

; if `date-alt` or `time-alt` is defined, clicking
; the module will toggle between formats
date-alt = %A, %d %B %Y
time-alt = %H:%M:%S
```

All comments are welcomed. Thanks in advance! :)

### PR DESCRIPTION
**Pull request by Lomadriel**
Fix #596.

A new attempt to implement this feature. This PR fixes the concurrency problem in #1353 by using a static mutex in the date class. Since the date class is the only one to support timezone, this shouldn't be a problem. However if a global clock is wanted I can add an utility function/class that will do the job.

TEAM EDIT: Closes #1293

### CODE REVIEW

**Comment by Lomadriel** [comment]
I just realized that `setenv` is not thread safe at all (I thought that `setenv` was thread safe if the modified environment variables were different but this is not the case).
I will add an utility function tomorrow.

**Comment by Lomadriel** [comment]
Okay so I added a `env_guard` class that behave like a `std::lock_guard`, in the constructor the environment variable is set and the original value is restored in the destructor. Moreover since this clock inherit of `std::lock_guard` a mutex is locked for the whole life of this `env_guard` and so it avoids concurrent call to `set_env`.

**Comment by Lomadriel** [comment]
Add `label-alt` and `format-alt`:

Documentation:
```ini

[module/date]
type = internal/date

; Seconds to sleep between updates
interval = 1.0

; See "http://en.cppreference.com/w/cpp/io/manip/put_time" for details on how to format the date string
; NOTE: if you want to use syntax tags here you need to use %%{...}
date = %Y-%m-%d%

; Optional time format
time = %H:%M

; if `date-alt` or `time-alt` is defined, clicking
; the module will toggle between formats
date-alt = %A, %d %B %Y
time-alt = %H:%M:%S

; Use the following command to list timezone
; ls /usr/share/zoneinfo/
; (Defaults: system timezone)
;timezone = 
timezone-alt = UTC

; Available tags:
; <label> (default)
; format = <label>

; Available tags:
; <label-alt> (default)
; format-alt = <label-alt>

; Available tokens:
;   %date%
;   %time%
; Default: %date%
label = %date% %time%
label-font = 3
label-foreground = #9A32DB

; Available tokens:
;   %date-alt%
;   %time-alt%
; Default: %date-alt%
label-alt = %date-alt% %time-alt%
label-alt-font = 3
label-alt-foreground = #9A32DB

```

**Comment by adkillick** [comment]
I would love to be able to have a UTC clock because I'm lazy with time conversion math when looking at server logs. Any chance this will be merged at some point?

**Comment by fosskers** [comment]
Until there is official support, we can get around this with a custom script that calls `date` directly. For example, here's what I use to show Japanese time alongside my machine's locale time:
```
[module/japan]
type = custom/script
interval = 5
exec = TZ=Asia/Tokyo date "+%H:%M %Z"
```

**Comment by roomcays** [comment]
I imagine using `time` and `time-alt` to switch between local and UTC time with a single click.

**Comment by patrick96** [comment]
Closing this because `setenv` is inherently unsafe in multi-threaded environments (no matter how many mutexes we use). See [this comment](https://github.com/polybar/polybar/pull/3160#issuecomment-2323348167) on a recent PR for more info

**Pull request closed without merging**
