### PR TITLE
Replace condition_variable from STL by a monotonic implementation.

### LINKED ISSUE #857: Modules stop updating when system clock moves backwards
I've noticed that some modules (such as the cpu, memory and date) stop updating after the system clock has moved backwards.

I dual boot with Windows which is constantly messing up my hardware time, however NTP fixes it when the system boots. This usually happens after Polybar has been launched though, and it ends up in this broken state.

I'm running 3.0.5 on Arch. If I get time this weekend I'll look into fixing it, but if you know where to start looking that would help :)

### LINKED ISSUE #1932: incorrect time after unhibernating
## Describe the issue
After unhibernating the computer, the display time is wrong.

## To Reproduce
- hibernate
- wait some time
- unhibernate

## Environment:
* WM: i3
* Distro: Arch Linux
* Output of `polybar -vvv`:
```
polybar 3.4.1

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wall -Wextra -Wpedantic -O3 -DNDEBUG
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now```

### PR DESCRIPTION
**Pull request by Lomadriel**
Fixes #857.

Add a re-implementation of `std::condition_variable` that uses the monotonic clock of POSIX.
Also replaces the call to `system_clock::now()` by `steady_clock::now()`.

EDIT:

Fixes #1932

### CODE REVIEW

**Comment by Lomadriel** [comment]
A little update concerning this PR, this bug has been fixed in GCC10 if I'm not wrong.

**Comment by patrick96** [comment]
I assume you are refering to [this](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=41861) bug. So that would mean we could scrap the use of our custom condition_variable but keep using `steady_clock`.

It's probably going to be a long time until gcc 10 is installed on most users computers but I'm not sure if maintaining our own version of `condition_variable` is appropriate, since the issue is easily fixed by restarting polybar in place.

Also I'm wondering whether or not clang is affected, I would assume not

**Comment by Lomadriel** [comment]
> I assume you are refering to [this](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=41861) bug. So that would mean we could scrap the use of our custom condition_variable but keep using `steady_clock`.

Yes it's this bug.

It's probably going to be a long time until gcc 10 is installed on most users computers but I'm not sure if maintaining our own version of condition_variable is appropriate, since the issue is easily fixed by restarting polybar in place.

Indeed that might be overkill for DST but I remember that someone had a problem with a clock that wasn't working properly but I can't find that issue anymore.

**Comment by patrick96** [comment]
You mean #857?

**Pull request closed without merging**
